baseURL = "https://savobajic.ca/"
languageCode = "en-us"
title = "Savo's Site"
enableGitInfo = true


[params]
  custom_css = ["css/style.css"]
  math = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
       unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

